# Generated by Django 4.2.1 on 2026-05-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_attempt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalpracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('screenshot', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to='exam_attempt.examattempt')),
            ],
        ),
    ]
