# Generated by Django 4.2.1 on 2026-05-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_exam_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='marks_per_question',
        ),
    ]
